[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  # Enable Next.js cache
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Handle 404 errors
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

# Configure build processing
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true 