[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  # Enable Next.js cache
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Handle client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Handle specific routes
[[redirects]]
  from = "/blog/*"
  to = "/blog/:splat"
  status = 200

[[redirects]]
  from = "/projects/*"
  to = "/projects/:splat"
  status = 200

[[redirects]]
  from = "/about"
  to = "/about"
  status = 200

[[redirects]]
  from = "/contact"
  to = "/contact"
  status = 200

# Handle 404 errors last
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

# Configure build processing
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true 